### PR TITLE
Updates to replace `lincbrain-cli` with `dandi`

### PR DESCRIPTION
**Pull request by kabilar**
Also, the example shown below did not work for me so I removed it.

```
dandi delete https://lincbrain.org/dandiset/101010/draft/files?location=rawdata%2Fsub-Ken2%2Fhorses
```

### CODE REVIEW

**Comment by ayendiki** [comment]
These are not real examples, they're Ken and Barbie examples :-D

________________________________
From: Kabilar Gunalan ***@***.***>
Sent: Friday, November 15, 2024 5:58 PM
To: lincbrain/linc-docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lincbrain/linc-docs] Updates to replace `lincbrain-cli` with `dandi` (PR #29)


        External Email - Use Caution

Also, the example shown below did not work for me so I removed it.

dandi delete https://lincbrain.org/dandiset/101010/draft/files?location=rawdata%2Fsub-Ken2%2Fhorses


________________________________
You can view, comment on, or merge this pull request online at:

  MailScanner has detected a possible fraud attempt from "secure-web.cisco.com" claiming to be https://github.com/lincbrain/linc-docs/pull/29<https://secure-web.cisco.com/1EijzCii-ggI8hzwofPE7Tkoq3hFFOsiqW7aNwHAFEEsp851sFxuxWIh19LyV0Xa489ECUIZ1awkgQ3PlNGIPjQ1Y86Wrh-LKBEAJith51dH3a1RZcm1vFWDA_b-LF6EJH4tDRc33s8WUfyu9PiPpl7UVQSzUwJ33qL-0dDcXGaFYRK6qsUukwMEUBu8ysqNacfWCr8DA8_XLS5QmCjs1zbvH8k5Ricm0noL4rlRIjFng6dZ5uNdPpWPgprjQFYZXluOEvDDekAOwx79o8LR7aIzhkKvkbUx5lMUJVYCrQeRzLVSsic4CqvjJrterecATV1-xS6AzZ3T5aWtPSDMIZA/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29>

Commit Summary

  *   618586b<https://secure-web.cisco.com/1nAlOghAodHNbRyz7Qe1LLr9Gbqg1XdobXFj1WN2KPJKvbLwlEWBMS8wDBeZF39sxnCYzU2NpmQgq1Lz1ef6ZIaBDQ4K-fB6kCz4D-unh0jWRT4CRLV5cDdzU9gkUdpgASRE0UX0WufxXPLMKPmmxd92P7gjxccdCKM4MXEwaGGjJqMZPeynBtK4Kv8IQJJlQhOEg0svAOiIacVXrSP7zHEkqNs-8BMczPnGyzrvgXmvX1C9fdijLi7ThHi03LQ0Q-W6hn0Iq84z6aTRESLBkYt2fAjvlEd8_8k5QOlUZBnwMp0pXFj-dSetUQZMwBqUN9qAAaef82_8Br6aOTmYkkQ/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29%2Fcommits%2F618586b3798f3a405c0daff58006a7b198bef1f1> Updates to replace `lincbrain-cli` with `dandi`
  *   f7e4832<https://secure-web.cisco.com/17p-41ZOAFb7l0iGvksJQOGnTtIyzs84yaqnrLA7zNAPokeo_kyjLXDZ0dbwfD2b7c3hi6uxr7H1Kk0hgR1RPP2PtnT_dkBnoqa48KAsSffKWLDCtsNq2oZmVBhh3ep6Ux4HBXrM2T0jFxYtoGiZV02s_dJ3COwbntNK9bqB-6stSjwzo7qb3lUBRqVg8lglDrcxZe6aJFObjyIpQLG14QuwyYueTR9hWDD8260SO79ZVhjqBPXYk3QIfNBkfFWAsvHQU3i2tpCtSueDcxFwSlrriyHlf-1hbi06_3L2Gltgs0MpDf4Tfl0Ko7S6VCENPZqV0903tKfC_TaHWZOFpkw/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29%2Fcommits%2Ff7e4832fe53fb138105112744265def7e968ca08> Merge branch 'main' of https://github.com/lincbrain/linc-docs

File Changes

(3 files<https://secure-web.cisco.com/1y49wfBxnqd5rPImgGJUZ0Bj8YUC56L9p0NDYFceq9TDX33BZ8JHGhY6dtey8vqeOPj8RRHHlQ8yHmZv0NjdGz-IrqS9D49kJ7dKsjU7hKS5VibPVmCcPaygEOHkRGtdNvqmv3GjHicU1FPXI_9IRNctwqGVmZgAVpMZMY2HD2dkNdFDNIk8SRoCH4evEW8QufKYlug5RalMkgBAdStUGcJ8JObD8Ozc0p7IkS9pK600VDTjjHA9Om86Y736vB8_HGV53FHuuU_GMpdQi5pDFTFFcnPtlYSjNcalk5Ok2N6y-vrcgcio8jRZByMbuvjnlHDzK7Gc6M7cJdP23ok6z5Q/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29%2Ffiles>)

  *   M docs/index.md<https://secure-web.cisco.com/1Z2duJ30XfBPTpdfHqbDiU1rVJjf4I5sSX4O0qdCGGZFy2bdb4GsYbhVqh4oyeD9wQSc7JHsMP2A933_bvwEdftUuJG6vwiQwGezyoK-7a3W8EZJYY-pIUEwPKyU2Z3QhQoGREy0OqayhNuHyQWLLWJdTXHiRBfBQ4pnapvEAlWtnKfpJrkhx_cmtEcIl6IzBzV4DAH3w0d1aIYX0VFFP3IuNJlUqhIrPzdElJxf1rHsc7tReebMmqk07gLz2x6BQGsokrzVXs2hscfN_5wlmVpB2Lpkx487il8MHJX5O6JUQTvyB9DaPVRy-V99H8WEoAJoWlrxHynKzmDgYI0rW9A/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29%2Ffiles%23diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6> (2)
  *   M docs/upload.md<https://secure-web.cisco.com/1JaprVytwY8RcNNYN3IdOh_S6EPPJmHkwlm101scjYfZYJCI1N6f3hejdN6TMnTgB2x4QR0W0TmZiQM3rWGSYT1ckwrmM8ZjAGn-7-eFsD26sgLnKgyiPiJbqoPcqDGgRb-eCSboGDES3lUSf8rVSJGaGK2FHastiYs4zQia_Xhq_Zov0QbcrMKlKh0XhOn7Vf2iV2DlG5SyfJL5MITXl0A3VMdH6oR0DgrOIWtdsby4ohhvZ_VgpUr7Zsz5rBxDnNbCsoZ9PwhJWlE6ww6mka6yeS2g1sOhyBxomZ2U7E-VC_EhPmAtxrKrxHIopVkOr0V2c4aK3sSpAYFwLHgbQxw/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29%2Ffiles%23diff-d4dda3bcbeb31e17b76840f7922808be0dd0717bd47dca4937df654f81c142ba> (22)
  *   M mkdocs.yml<https://secure-web.cisco.com/1Dc3UKdP10x30Egt7uH-a2NBFmR2uFqUD6wa4cvT3YyVyRS4KlhK9YI_cFignOA3o4qB4IWaQ5XqfkgMXnATdtGXpcBQ8Opg_8neYgTqvhimgCfhhn8drNe6RJVEOTw-AP9x7Ftrpa-9P4rZobYZen3h2Xzjduk-dccPK90UND0QenpuzBRY__cdWKTyVtANeVFElx0B_OE8m8Vpf9lRmHXBOP2QMuhWyDp0j7uCO38YZMwIP9ocMqikP1oONYJhVZ6Mp2Pn1bj8QOzlzT_00EGqP6xWeurcm6YkzEyeO9d3_TMfM2TU9N4wS1PJJngaHuLzDHh2EaYzDlQuuTvdr5A/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29%2Ffiles%23diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2> (2)

Patch Links:

  *   MailScanner has detected a possible fraud attempt from "secure-web.cisco.com" claiming to be https://github.com/lincbrain/linc-docs/pull/29.patch<https://secure-web.cisco.com/1pYKbiEM8wCwEOPpgBd9Bv993il6qAUFtkHJjP6eyk6OZw8k2HEbRMiQqO7R7xAD4u3BH_mI3BOxAor8nS7C7Y7niZ6GjI7uytldxE-r_N4yDuDMxZU21ZTaig1E2L5GvhXKzuCMMhNwy5bDGZ6DK9NfAFZ_GtOAUhdgftjCITnM9o_U9WPiTocf2TGAb3qpfEZqzJC7an9qN-Vig9tG4GrjVjSX0Roef038CAg1Ns6DH5pKmOZge-A5amkzp0wIxZaUkhuZSPDL0mCJosGKFEn8hmLd9DHCb7iyNlId1RS0eLpSo820mtbnHRTxek43vnk63kz4HTh17IgsiWmMAyQ/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29.patch>
  *   MailScanner has detected a possible fraud attempt from "secure-web.cisco.com" claiming to be https://github.com/lincbrain/linc-docs/pull/29.diff<https://secure-web.cisco.com/1fKpv1oO3RDdNW_CRLZBlxBuHg5Hjd5IJn-D52fSuKUlpQkWLxa4XxfmytAD3R47MKOLnomTubj-NRLP_u8YaHJb4OpG-ziJ59P9ZapngPAi4aIXG98ni1AMVS-jpBdoO98vSZ-gT7Te-Kk2-rZ25Tb_Uu7ONKnmmUtcMnv6EDq5kuqqZdmA3PrDmx5oX8bBBzDWCPhHpKqUf435WXW-XX-UfZV_myEljxd-PYNcecFekJ42i-0_w566V4-W1DjVboCZNNvxzzQvnq3CZkZY0qf-D4WVU2AMX6dgLLmzAVQX1kKcUjBIxaoVxMkIxxlaAHk8n6s9M-TfB9Ip-yYGWCw/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29.diff>

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1EijzCii-ggI8hzwofPE7Tkoq3hFFOsiqW7aNwHAFEEsp851sFxuxWIh19LyV0Xa489ECUIZ1awkgQ3PlNGIPjQ1Y86Wrh-LKBEAJith51dH3a1RZcm1vFWDA_b-LF6EJH4tDRc33s8WUfyu9PiPpl7UVQSzUwJ33qL-0dDcXGaFYRK6qsUukwMEUBu8ysqNacfWCr8DA8_XLS5QmCjs1zbvH8k5Ricm0noL4rlRIjFng6dZ5uNdPpWPgprjQFYZXluOEvDDekAOwx79o8LR7aIzhkKvkbUx5lMUJVYCrQeRzLVSsic4CqvjJrterecATV1-xS6AzZ3T5aWtPSDMIZA/https%3A%2F%2Fgithub.com%2Flincbrain%2Flinc-docs%2Fpull%2F29>, or unsubscribe<https://secure-web.cisco.com/1iN0CQtcwivd8q2KHI-D3pLB7kHnvtWW4OkY6GoHZABVFMmKZDaplgzg9zkVA7iXSAEDWSfWGYVBLqO-ooFHsND8JtI79To8W3mDOkmYmhglZ74jvXmZK7767XWUU1V0eEAVQkJcCImmxLMNz4ndmWNgt9cqaWTX3MtGRDvwstDLXtCZyIyaU2y0bWVyYWzP5XDOfF020LXgNfhdnJ1VZVtb3SylQ6J-4Pxco3NB-5Et6_KrXsFEekOUE7RscqaF69lJVWRy7BTC0-dKc8N3cwPb_hbQJ5XIcaHdsKVy1fInmjioESoE2dM_SyN-9aRJlVoNwKAzv-K_BVkwdHYoVkQ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADU34V54THO2555VOAKWCV32AZ4BBAVCNFSM6AAAAABR4DXVGKVHI2DSMVQWIX3LMV43ASLTON2WKOZSGY3DGNBRG44TINI>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/lincbrain/linc-docs/pull/29", "url": "https://github.com/lincbrain/linc-docs/pull/29", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by satra** [comment]
image

**Comment by kabilar** [comment]
> These are not real examples, they're Ken and Barbie examples :-D

Haha, oh I think this is a windows/mac issue.  I tried it with a real path but it didn't work until now when I added quotes:

```bash
dandi delete -i linc "https://lincbrain.org/dandiset/000044/draft/files?location=icephys"
```

I will revert those changes.

**Comment by kabilar** [comment]
Also, `dandi delete -i linc ./dataset_description.json` and `dandi delete -i linc "./dataset_description.json"` only deleted the remote asset so that is why I changed the text.

**Review by aaronkanzer — APPROVED** [review]

**Pull request merged**
